prog:Perso.o main.o
		gcc perso.o main.o -o prog -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf

main.o:main.c
		gcc -c main.c -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf

Perso.o:perso.c
		gcc -c perso.c -g -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf
